# This file is used by the question generation script
# Format for each field MUST be: "{field_name} - {field_description}"

stock_data = [
    "stock_data.date_ex_dividend - This represents the ex-dividend date associated with a cash income dividend payment. The data displayed is based upon the dividend whose PAYMENT DATE is most recent to the user's request date.",
    "stock_data.total_return_index - A return index is available for individual equities. This shows a theoretical growth in value of a share holding over a specified period, assuming that dividends are re-invested to purchase additional units of an equity or unit trust at the closing price applicable on the ex-dividend date.",
    "stock_data.price_intraday_low - This is the lowest price achieved on the trading day.",
    "stock_data.price_intraday_high - This is the highest price achieved on the trading day.",
    "stock_data.price_earnings_ratio - This is the price divided by the earnings rate per share at the required date.",
    "stock_data.price -  The latest trade price, settlement value or closing value. Assume this is the current price.",
    "stock_data.market_capitalization - Market Capitalization or Market Value is the share price multiplied by the number of ordinary shares in issue. The amount in issue is updated whenever new tranches of stock are issued or after a capital change. Market cap is displayed in millions of units of local currency.",
    "stock_data.dividend_yield - The dividend yield expresses the dividend per share as a percentage of the share price. The underlying dividend is calculated according to the same principles as datatype DPSC (Dividend per share, current rate) in that it is based on an anticipated annual dividend and excludes special or once-off dividends. Dividend yield is calculated on gross dividends (including tax credits) where available.",
    "stock_data.book_value_per_share - BOOK VALUE PER SHARE represents the book value (common equity )at the end of the last calendar quarter for U.S. corporations.",
    "stock_data.common_shares_outstanding - COMMON SHARES OUTSTANDING represent the number of shares outstanding at the company's year end. It is the difference between issued shares and treasury shares.",
    "stock_data.company_name - COMPANY NAME represents the legal name of the company as reported in the 10-K for U.S. companies.",
    "stock_data.cogs - Cost Of Goods Sold represents the direct costs incurred in producing or acquiring the goods that a company sells to generate revenue. COGS includes expenses directly associated with the production or purchase of goods, such as the cost of raw materials, direct labor, and manufacturing overhead.",
    "stock_data.current_assets_total - CURRENT ASSETS - TOTAL represents cash and other assets that are reasonably expected to be realized in cash, sold or consumed within one year or one operating cycle.Generally, it is the sum of cash and equivalents, receivables, inventories, prepaid expenses and other current assets.",
    "stock_data.current_liabilities_total - CURRENT LIABILITIES - TOTAL represent debt or other obligations that the company expects to satisfy within one year.",
    "stock_data.employees - EMPLOYEES represent the number of both full and part time employees of the company.",
    "stock_data.ebitda - EARNINGS BEFORE INTEREST, TAXES, DEPRECIATION & AMORTIZATION (EBITDA) represent the earnings of a company before interest expense, income taxes and depreciation. It is calculated by taking the pre-tax income and adding back interest expense on debt and depreciation, depletion and amortization and subtracting interest capitalized.",
    "stock_data.enterprise_value - ENTERPRISE VALUE(EV) = Market Capitalization at fiscal year end date + Preferred Stock + Minority Interest + Total Debt minus Cash.",
    "stock_data.eps_12m_forward - 12 Forward Month Earnings per Share based on projections of a company's earnings (net income) over the next twelve months",
    "stock_data.eps_12m_trailing - Earnings per share for the past 12 months, based on published accounts of net income.",
    "stock_data.general_industry_classification - General Industry Classification Standard (GICS) represents the company's general industry classification: Energy, Materials, Industrials, Consumer Discretionary, Consumer Staples, Health Care, Financials, Information Technology, Communication Services, Utilities, and Real Estate.",
    "stock_data.inventories_days_held - Inventories Days Held is equal to 365 / (Cost of Goods Sold (excl Depreciation) / (Average of Last Year’s and Current Year’s Inventories ) .",
    "stock_data.long_term_debt - LONG TERM DEBT represents all interest bearing financial obligations, excluding amounts due within one year. It is shown net of premium or discount.",
    "stock_data.net_interest_income - NET INTEREST INCOME represents the difference between the total interest income and total interest expense of the bank.",
    "stock_data.net_sales_or_revenues - NET SALES OR REVENUES represent gross sales and other operating revenue less discounts, returns and allowances.",
    "stock_data.nonoperating_interest_income - NON-OPERATING INTEREST INCOME represents income generated from interest bearing investments not related to the operating activities of the company. ",
    "stock_data.operating_income - OPERATING INCOME represents the difference between sales and total operating expenses",
    "stock_data.operating_expenses_total - OPERATING EXPENSES - TOTAL represents the sum of all expenses related to operations.",
    "stock_data.research_and_development - RESEARCH AND DEVELOPMENT EXPENSE represents all direct and indirect costs related to the creation and development of new processes, techniques, applications and products with commercial possibilities.",
    "stock_data.selling_general_and_administrative_expenses - SELLING, GENERAL & ADMINISTRATIVE EXPENSES (SG&A) represents expenses not directly attributable to the production process but relating to selling, general and administrative functions.",
    "stock_data.ticker_symbol - TICKER SYMBOL represents a symbol used to identify the company on the stock exchanges where it is listed.",
    "stock_data.total_assets - TOTAL ASSETS represent the sum of total current assets, long term receivables, investment in unconsolidated subsidiaries, other investments, net property plant and equipment and other assets.",
    "stock_data.total_liabilities - TOTAL LIABILITIES represent all short and long term obligations expected to be satisfied by the company.",
    "stock_data.total_shareholders_equity - TOTAL SHAREHOLDERS’ EQUITY represents the sum of Preferred Stock and Common Shareholders’ Equity.",
    "stock_data.volume_weighted_avg_price - Volume Weighted Average Price is a trading indicator that calculates the average price at which a stock has been traded throughout a specific trading day, taking into account both the volume and price of each transaction.",
    "stock_data.beta - Beta is a measure of a stock's volatility or sensitivity to market movements, indicating how much the stock's price tends to move in relation to changes in the broader market.",
    "stock_data.price_2_intrinsic_value - a financial metric that compares the market price of a stock or asset to its estimated intrinsic value, which represents the perceived true value of the company or asset based on fundamental analysis, helping investors assess whether the stock is overvalued or undervalued.",
    "stock_data.salaries_benefits_expenses - expenses refer to the financial resources allocated by a company to compensate employees for their work, including wages, bonuses, insurance, retirement plans, and other perks.",
    "stock_data.recommendation_consensus - Acts as the main rating of the stock. Recommendation consensus - the average recommendation of analysts on a 1-5 scale.  Between 1 & 1.49: Strong Buy, Between 1.5 & 2.49: Buy, Between 2.5 & 3.49: Hold, Between 3.5 $ 4.49: Underperform, Between 4.5 & 5: Sell.",
]

market_data = [
    "market_data.energy - Energy Sector Index",
    "market_data.real_estate - REAL ESTATE SECTOR Index",
    "market_data.it - Information Technology Sector Index",
    "market_data.consumer_disc - Consumer Discretionary Sector Index",
    "market_data.consumer_staples - Consumer Staples Sector Index",
    "market_data.health_care - Health Care Sector Index",
    "market_data.materials - Materials Sector Index",
    "market_data.financials - Financials Sector Index",
    "market_data.utilities - Utilities Sector Index",
    "market_data.industrials - Industrials Sector Index",
    "market_data.communications_services - COMMUNICATIONS SERVICES SECTOR Index",
    "market_data.s&p500 - S&P 500, this is the stock market benchmark index",
    "market_data.nasdaq100 - index composed of the top 100 non-financial companies listed on the NASDAQ stock exchange, serving as a benchmark for investors to track the performance of large-cap technology and growth-oriented companies.",
    "market_data.volatility_index - a measure of market volatility and investor sentiment, commonly referred to as the 'fear gauge' indicating the expected level of price fluctuations in the stock market.",
    "market_data.growth_index - Index of Growth stocks refer to shares of companies that are expected to experience significant increases in revenue, earnings, or market share in the future, often characterized by a focus on expanding operations, investing in research and development, and reinvesting profits for further growth rather than distributing dividends.",
]

economic_indicators = [
    "economic_indicators.cpi - CPI - ALL URBAN: ALL ITEMS  SA. The Consumer Price Index (CPI) is a measure of the average change over time in the prices of consumer items - goods and services that people buy for day-to-day living. The quantity and quality of these items are kept essentially unchanged between major revisions so that only price changes will be measured. All taxes directly associated with the purchase and use of items are included in the index. The CPI is a complex construct that combines economic theory with sampling and other statistical techniques and uses data from several surveys to produce a timely and precise measure of average price change for the consumption sector of the American economy. The U.S. Bureau of Labor Statistics publishes a new set of relative importances of components in the consumer price index in December of each year.",
    "economic_indicators.gdp - GDP (AR)  National Product Account, Gross Domestic Product, Overall, Total, Constant Prices, AR, SA, USD, 2012 Chained Prices. Gross domestic product (GDP) is the market value of goods and services produced by labor and property in the United States, regardless of nationality; GDP replaced gross national product (GNP) as the primary measure of U.S. production in 1991. Series are in billions of dollars and seasonally adjusted at annual rates.",
    "economic_indicators.fed_funds_rate - FEDERAL FUNDS TARGET RATE. United States, Policy Rates, Federal Funds Target Rate, The Federal Reserve's objective for open market operations has varied over the years and in 1995 it began to explicitly state its target level for the federal funds rate.",
    "economic_indicators.ism_mfg - ISM PURCHASING MANAGERS INDEX (MFG SURVEY), Institute for Supply Management Monthly SA. United States, Business Surveys, Institute for Supply Management Manufacturing, Purchasing Managers Index Total, SA, Index. The Manufacturing ISM Report On Business is based on data compiled from purchasing and supply executives nationwide. Membership of the Manufacturing Business Survey Committee is diversified by NAICS, based on each industry's contribution to gross domestic product (GDP). Survey responses reflect the change, if any, in the current month compared to the previous month. For each of the indicators measured (New Orders, Backlog of Orders, New Export Orders, Imports, Production, Supplier Deliveries, Inventories, Customers' Inventories, Employment and Prices), this report shows the percentage reporting each response, the net difference between the number of responses in the positive economic direction (higher, better and slower for Supplier Deliveries) and the negative economic direction (lower, worse and faster for Supplier Deliveries), and the diffusion index. Responses are raw data and are never changed. The diffusion index includes the percent of positive responses plus one-half of those responding the same (considered positive).",
    "economic_indicators.personal_consumption_expenditure - GDP (AR), BEA - Bureau of Economic Analysis, U.S. Department of Commerce Quarterly Current prices, SA. United States, Price Index, Personal Consumption Expenditure, Overall, Total, SA, Index, 2012 = 100. Index that is based on the linking (chaining) of indexes to create a time series. Annual chain-type Fisher indices are used in BEA’s national income and product accounts (NIPAs) whereby Fisher ideal price indices are calculated using the weights of adjacent years. Those annual changes are then multiplied (chained) together, forming the chain-type index time series.",
    "economic_indicators.unemployment_rate - UNEMPLOYMENT RATE, Bureau of Labor Statistics, U.S. Department of Labor Monthly SA. United States, Unemployed, Rate, Total, SA. The Current Population Survey (CPS; household survey) provides information on the labor force, employment, and unemployment. It is a sample survey of about 60,000 eligible households conducted by the U.S. Census Bureau for the U.S. Bureau of Labor Statistics (BLS). The reference period is generally the calendar week that contains the 12th day of the month. The sample is selected to reflect the entire civilian noninstitutional population. Based on responses to a series of questions on work and job search activities, each person 16 years and over in a sample household is classified as employed, unemployed, or not in the labor force. The unemployment rate is the number unemployed as a percent of the labor force. The labor force participation rate is the labor force as a percent of the population, and the employment-population ratio is the employed as a percent of the population.",
    "economic_indicators.ism_non_mfg - ISM NONMANUFACTURERS SURVEY INDEX: COMPOSITE, ISM - Institute for Supply Management Monthly SA. United States, Business Surveys, Institute for Supply Management Non-Manufacturing, NMI / Purchasing Managers Index, SA, Index. The Non-Manufacturing ISM Report On Business is based on data compiled from purchasing and supply executives nationwide. Membership of the Non-Manufacturing Business Survey Committee is diversified by NAICS, based on each industry's contribution to gross domestic product (GDP). Diffusion indexes have the properties of leading indicators and are convenient summary measures showing the prevailing direction of change and the scope of change. An index reading above 50 percent indicates that the non-manufacturing economy in that index is generally expanding; below 50 percent indicates that it is generally declining. Supplier Deliveries is an exception. A Supplier Deliveries Index above 50 percent indicates slower deliveries and below 50 percent indicates faster deliveries",
    "economic_indicators.consumer_confidence - CONSUMER CONFIDENCE INDEX, The Conference Board Monthly SA. United States, Consumer Surveys, Conference Board, Consumer Confidence, SA, Index, 1985 = 100. In 1967, The Conference Board began the Consumer Confidence Survey (CCS) as a mail survey conducted every two months; in June 1977, the CCS began monthly collection and publication. The CCS has maintained consistent concepts, definitions, questions, and mail survey operations since its inception. . The Conference Board Consumer Confidence Index ® (CCI) is based on consumers’ perceptions of current business and employment conditions, as well as their expectations for six months hence regarding business conditions, employment, and income. Each of the five CCS survey questions has three response options: positive, negative, or neutral. For each question, the positive figure is divided by the sum of the positive and negative to yield a proportion, called the 'relative' value. The average relative value for the calendar year 1985 is then used as a benchmark to yield the index value for a question.",
    "economic_indicators.industrial_production - INDUSTRIAL PRODUCTION - TOTAL INDEX SA,Federal Reserve, United States Monthly Volume or constant price value index, SA. The Federal Reserve's monthly index of industrial production and the related capacity indexes and capacity utilization rates cover manufacturing, mining, and electric and gas utilities. The industrial sector, together with construction, accounts for the bulk of the variation in national output over the course of the business cycle. The industrial detail provided by these measures helps illuminate structural developments in the economy. The production index measures real output and is expressed as a percentage of real output in a base year, currently 2017.",
    "economic_indicators.conf_board_leading_indicators - THE CONFERENCE BOARD LEADING ECONOMIC INDICATORS INDEX, The Conference Board Monthly SA . United States, Leading Index, Total, SA, Index, 2016 = 100. The composite indexes are the key elements in an analytic system designed to signal peaks and troughs in the business cycle. Historically, the cyclical turning points in the leading index have occurred before those in aggregate economic activity. The leading index is the composite average of the following indicators: 1. Average weekly hours, manufacturing; 2. Average weekly initial claims for unemployment insurance; 3. Manufacturers' new orders, consumer goods and materials; 4. Vendor performance, slower deliveries diffusion index; 5. Manufacturers' new orders, nondefense capital goods; 6. Building permits, new private housing units; 7. Stock prices, 500 common stocks; 8. Money supply, M2; 9. Interest rate spread, 10-year Treasury bonds less federal funds; and 10. Index of consumer expectations.",
    "economic_indicators.10Y_ust_yield - USA 10-year Government Benchmark bond yield - Yield of 10 year US Treasury Government Bond",
]

news_source = [
    "news_data_source - The news data is a data warehouse where we store all news obtained from various vetted sources. Each news item has keywords and date.",
]

external_data_source = [
    "external_data_source - all stock/finance related data and information that is not contained in a refinitive database or vetted news warehouse. This includes the general internet and social media.",
]

all_fields = stock_data + market_data + economic_indicators + news_source + external_data_source
