python llama_2_lora_tune.py \
 --model_path /home/adrianw/hf \
 --save_path /home/adrianw/tuned \
 --r 8 \
 --lora_dropout 0.05 \
 --lora_alpha 32 \
 --batch_size 8 \
 --epochs 50 \
 --lr 0.0001 \
 --max_length 128 \
 --dataset_path /home/adrianw/ConFIRM/datasets/mixed/ConFIRM_QAset_559n_mixed.csv
