python scripts/llama_2_lora_tune.py \
 --model_path $MODEL_PATH \
 --save_path $SAVE_PATH \
 --r 8 \
 --lora_dropout 0.05 \
 --lora_alpha 32 \
 --batch_size 8 \
 --epochs 50 \
 --lr 0.0003 \
 --max_length 64 \
 --dataset_path $DS_PATH
